// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAALP9hEsd1z7-MLpke9UibWLBFmhKY4X8',
    appId: '1:313906554152:web:6b568956c90420384b9c1d',
    messagingSenderId: '313906554152',
    projectId: 'iotcw-3bae1',
    authDomain: 'iotcw-3bae1.firebaseapp.com',
    storageBucket: 'iotcw-3bae1.firebasestorage.app',
    measurementId: 'G-5R4F8J4P43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOELfQOkZFIlw_bindL7Y8jTIyWtEJmk',
    appId: '1:313906554152:android:89a2c1a1643058114b9c1d',
    messagingSenderId: '313906554152',
    projectId: 'iotcw-3bae1',
    storageBucket: 'iotcw-3bae1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWwbCDRwQkxCpTild2gCJwjAs8S-nV6SU',
    appId: '1:313906554152:ios:7d85b09818d3d16a4b9c1d',
    messagingSenderId: '313906554152',
    projectId: 'iotcw-3bae1',
    storageBucket: 'iotcw-3bae1.firebasestorage.app',
    iosBundleId: 'com.example.iotCw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWwbCDRwQkxCpTild2gCJwjAs8S-nV6SU',
    appId: '1:313906554152:ios:7d85b09818d3d16a4b9c1d',
    messagingSenderId: '313906554152',
    projectId: 'iotcw-3bae1',
    storageBucket: 'iotcw-3bae1.firebasestorage.app',
    iosBundleId: 'com.example.iotCw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAALP9hEsd1z7-MLpke9UibWLBFmhKY4X8',
    appId: '1:313906554152:web:280f4fe778dfa4e84b9c1d',
    messagingSenderId: '313906554152',
    projectId: 'iotcw-3bae1',
    authDomain: 'iotcw-3bae1.firebaseapp.com',
    storageBucket: 'iotcw-3bae1.firebasestorage.app',
    measurementId: 'G-FN381L5NP4',
  );
}
